name: Lila integration test

on:
  - push
  - pull_request

jobs:
  lila:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:ci2
        options: --restart=always
    steps:
      - name: Checkout berserk
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          ./integration/run.sh
